pipelineName: docs-tidb-operator-merge-pipeline 
repo: pingcap/docs-tidb-operator
defaultRef: master 
triggers:
  push:
      onBranch:
      - "master"
      - "release-*"
tasks:
    - taskName: "docs-tidb-operator-build-pdf" 
      checkerName: "common-check" 
      params:  
        shellScript: |
          sudo pip3 install boto3
          sudo pip3 install awscli
          printf "%s\n" ${AWS_ACCESS_KEY} ${AWS_SECRET_KEY} ${AWS_REGION} "json" | aws configure
          grep -RP '\t' *  | tee | grep '.md' && exit 1; echo ok
          python3 scripts/merge_by_toc.py en/; python3 scripts/merge_by_toc.py zh/;
          scripts/generate_pdf.sh
          sudo bash -c 'echo "222.222.95.49 uc.qbox.me" >> /etc/hosts';
          if [ "${TARGET_BRANCH}" = "master" ]; then
            python3 scripts/upload.py output_en.pdf tidb-in-kubernetes-dev-en-manual.pdf;
            python3 scripts/upload.py output_zh.pdf tidb-in-kubernetes-dev-zh-manual.pdf;
          elif [ "${TARGET_BRANCH}" = "release-1.2" ]; then
            python3 scripts/upload.py output_en.pdf tidb-in-kubernetes-stable-en-manual.pdf;
            python3 scripts/upload.py output_zh.pdf tidb-in-kubernetes-stable-zh-manual.pdf;
          elif [ "${TARGET_BRANCH}" = "release-1.1" ]; then
            python3 scripts/upload.py output_en.pdf tidb-in-kubernetes-v1.1-en-manual.pdf;
            python3 scripts/upload.py output_zh.pdf tidb-in-kubernetes-v1.1-zh-manual.pdf;
          elif [ "${TARGET_BRANCH}" = "release-1.0" ]; then
            python3 scripts/upload.py output_en.pdf tidb-in-kubernetes-v1.0-en-manual.pdf;
            python3 scripts/upload.py output_zh.pdf tidb-in-kubernetes-v1.0-zh-manual.pdf;
          fi
      credentials:
        - jenkinsID: docs-cn-aws-ak
          key: AWS_ACCESS_KEY
        - jenkinsID: docs-cn-aws-sk
          key: AWS_SECRET_KEY
        - jenkinsID: docs-cn-aws-region
          key: AWS_REGION
        - jenkinsID: docs-cn-aws-bn
          key: AWS_BUCKET_NAME
        - jenkinsID: docs-cn-qiniu-ak
          key: QINIU_ACCESS_KEY
        - jenkinsID: docs-cn-qiniu-sk
          key: QINIU_SECRET_KEY
        - jenkinsID: docs-cn-qiniu-bn
          key: AWS_REGION
        - jenkinsID: docs-cn-aws-bn
          key: QINIU_BUCKET_NAME
      image: "hub.pingcap.net/jenkins/docs-cn-checker:v0.0.1"
      resources:  
          requests:
              memory: "1000Mi"
              cpu: "500m"
          limits:
              memory: "2000Mi"
              cpu: "1000m"
