pipelineName: migration-verify-pipeline 
repo: tikv/migration
defaultRef: master 
triggers:
  pullRequest:
      onBranch:
      - "master"
      - "release-*"
      onComment:
      - "/verify"
tasks:
    - taskName: "br-lint" 
      checkerName: "lint-check" 
      params:  
        shellScript: |
            cd br/
            make check
      image: "hub.pingcap.net/jenkins/centos7_golang-1.16:latest"  
      resources:  
          requests:
              memory: "1000Mi"
              cpu: "500m"
          limits:
              memory: "20000Mi"
              cpu: "20000m"

    - taskName: "br-build" 
      checkerName: "build-check" 
      params:  
        shellScript: |
            cd br/
            make build_br
        outputDir : "br/bin/"
      image: "hub.pingcap.net/jenkins/centos7_golang-1.16:latest"  
      resources:  
          requests:
              memory: "8000Mi"
              cpu: "4000m"
          limits:
              memory: "8000Mi"
              cpu: "4000m"

    - taskName: "br-ut" 
      checkerName: "ut-check" 
      params:  
        shellScript: |
            make unit_test_in_verify_ci
        utReport: br-junit-report.xml
        covReport: /br_cov.unit_test.out
      image: "hub.pingcap.net/jenkins/centos7_golang-1.16:latest"  
      resources:  
          requests:
              memory: "8000Mi"
              cpu: "4000m"
          limits:
              memory: "30000Mi"
              cpu: "16000m"

    - taskName: "cdc-ut" 
      checkerName: "ut-check" 
      params:  
        shellScript: |
            cd cdc/
            make unit_test_in_verify_ci
        utReport: cdc-junit-report.xml
        covReport: cdc-coverage.xml
      image: "hub.pingcap.net/jenkins/centos7_golang-1.16:latest"  
      resources:  
          requests:
              memory: "8000Mi"
              cpu: "4000m"
          limits:
              memory: "30000Mi"
              cpu: "16000m"

    - taskName: "cdc-lint" 
      checkerName: "lint-check" 
      params:  
        shellScript: |
            cd cdc/
            make check-static
      image: "hub.pingcap.net/jenkins/centos7_golang-1.16:latest"  
      resources:  
          requests:
              memory: "1000Mi"
              cpu: "500m"
          limits:
              memory: "20000Mi"
              cpu: "20000m"

    - taskName: "cdc-build" 
      checkerName: "build-check" 
      params:  
        shellScript: |
            cd cdc/
            make cdc
        outputDir : "cdc/bin/bin/"
      image: "hub.pingcap.net/jenkins/centos7_golang-1.16:latest"  
      resources:  
          requests:
              memory: "8000Mi"
              cpu: "4000m"
          limits:
              memory: "8000Mi"
              cpu: "4000m"

    - taskName: "br-gosec" 
      checkerName: "gosec-check" 
      params:  
        shellScript: |
            cd br/
            gosec -fmt=junit-xml -out=results.xml -stdout -verbose=text -exclude=G103,G104,G204,G304,G307,G401,G404,G501,G505,G601 dm/... || true
        reportDir: results.xml
      image: "hub.pingcap.net/jenkins/centos7_golang-1.16:latest"  
      resources:  
          requests:
              memory: "2000Mi"
              cpu: "1000m"
          limits:
              memory: "8000Mi"
              cpu: "4000m"

    - taskName: "cdc-gosec" 
      checkerName: "gosec-check" 
      params:  
        shellScript: |
            cd cdc/
            gosec -fmt=junit-xml -out=results.xml -stdout -verbose=text -exclude=G103,G104,G204,G304,G307,G401,G404,G501,G505,G601 -exclude-dir=dm ./... || true
        reportDir: results.xml
      image: "hub.pingcap.net/jenkins/centos7_golang-1.16:latest"  
      resources:  
          requests:
              memory: "2000Mi"
              cpu: "1000m"
          limits:
              memory: "8000Mi"
              cpu: "4000m"