pipelineName: docs-verify-pipeline 
repo: pingcap/docs
defaultRef: master 
triggers:
  pullRequest:
      onBranch:
      - "master"
      - "release-*"
      onComment:
      - "/verify"
tasks:
    - taskName: check file encoding
      checkerName: "common-check" 
      params:  
        shellScript: |
            git remote add upstream https://github.com/pingcap/docs.git
            git fetch upstream
            wget https://raw.githubusercontent.com/pingcap/docs/master/scripts/check-file-encoding.py
            python3 check-file-encoding.py $(git diff-tree --name-only --no-commit-id -r upstream/${TARGET_BRANCH}..HEAD -- '*.md' ':(exclude).github/*')
      image: "node:lts"  
      resources:  
          requests:
              memory: "4000Mi"
              cpu: "2000m"
          limits:
              memory: "4000Mi"
              cpu: "2000m"

    - taskName: check git conflicts
      checkerName: "common-check" 
      params:  
        shellScript: |
            git remote add upstream https://github.com/pingcap/docs.git
            git fetch upstream
            wget https://raw.githubusercontent.com/pingcap/docs/master/scripts/check-conflicts.py
            python3 check-conflicts.py $(git diff-tree --name-only --no-commit-id -r upstream/${TARGET_BRANCH}..HEAD -- '*.md' '*.yml' '*.yaml')
      image: "node:lts"  
      resources:  
          requests:
              memory: "4000Mi"
              cpu: "2000m"
          limits:
              memory: "4000Mi"
              cpu: "2000m"

    - taskName: Lint edited files
      checkerName: "common-check" 
      params:  
        shellScript: |
            npm install -g markdownlint-cli@0.17.0
            git remote add upstream https://github.com/pingcap/docs.git
            git fetch upstream
            markdownlint $(git diff-tree --name-only --no-commit-id -r upstream/${TARGET_BRANCH}..HEAD -- '*.md' ':(exclude).github/*')
      image: "node:lts"  
      resources:  
          requests:
              memory: "4000Mi"
              cpu: "2000m"
          limits:
              memory: "4000Mi"
              cpu: "2000m"

    # - taskName: Check internal links
    #   checkerName: "common-check" 
    #   params:  
    #     shellScript: |
    #         ./scripts/verify-links.sh
    #   image: hub.pingcap.net/jenkins/node:lts-with-ssh
    #   resources:  
    #       requests:
    #           memory: "4000Mi"
    #           cpu: "2000m"
    #       limits:
    #           memory: "4000Mi"
    #           cpu: "2000m"

    # - taskName: Check internal link anchorss
    #   checkerName: "common-check" 
    #   params:  
    #     shellScript: |
    #         ./scripts/verify-link-anchors.sh
    #   image: hub.pingcap.net/jenkins/node:lts-with-ssh
    #   resources:  
    #       requests:
    #           memory: "4000Mi"
    #           cpu: "2000m"
    #       limits:
    #           memory: "4000Mi"
    #           cpu: "2000m"

    - taskName: "Check control characters"
      checkerName: "common-check" 
      params:  
        shellScript: |
            git remote add upstream https://github.com/pingcap/docs.git
            git fetch upstream
            wget https://raw.githubusercontent.com/pingcap/docs/master/scripts/check-control-char.py
            python3 check-control-char.py $(git diff-tree --name-only --no-commit-id -r upstream/${TARGET_BRANCH}..HEAD -- '*.md' ':(exclude).github/*')
      image: node:lts
      resources:  
          requests:
              memory: "4000Mi"
              cpu: "2000m"
          limits:
              memory: "4000Mi"
              cpu: "2000m"

    - taskName: "Check unclosed tags"
      checkerName: "common-check" 
      params:  
        shellScript: |
            git remote add upstream https://github.com/pingcap/docs.git
            git fetch upstream
            wget https://raw.githubusercontent.com/pingcap/docs/master/scripts/check-tags.py
            python3 check-tags.py $(git diff-tree --name-only --no-commit-id -r upstream/${TARGET_BRANCH}..HEAD -- '*.md' ':(exclude).github/*')
      image: node:lts
      resources:  
          requests:
              memory: "4000Mi"
              cpu: "2000m"
          limits:
              memory: "4000Mi"
              cpu: "2000m"

    - taskName: "Check manual line breaks"
      checkerName: "common-check" 
      params:  
        shellScript: |
            git remote add upstream https://github.com/pingcap/docs.git
            git fetch upstream
            wget https://raw.githubusercontent.com/pingcap/docs/master/scripts/check-manual-line-breaks.py
            python3 check-manual-line-breaks.py $(git diff-tree --name-only --no-commit-id -r upstream/${TARGET_BRANCH}..HEAD -- '*.md' ':(exclude).github/*')
      image: node:lts
      resources:  
          requests:
              memory: "4000Mi"
              cpu: "2000m"
          limits:
              memory: "4000Mi"
              cpu: "2000m"